name: Update badges

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: sagar-chamling-rai
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREDLY_SORT: POPULAR
          BADGE_SIZE: 80
